version: '3.8'

services:
  core:
    build:
      context: ../app
      target: app
    restart: always
    command: /bin/bash -c 'python3 manage.py'
    ports:
      - "8080:8080"
    volumes:
      - ../app:/mnt
    working_dir: /mnt/
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}

  storage:
    build:
      context: ../celeblur
      target: storage
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000