version: '3.8'

services:
  core:
    build:
      context: ../app
      target: app
    restart: always
    command: /bin/bash -c 'python3 manage.py'
    ports:
      - "80:8080"
    working_dir: /mnt/
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}

  storage:
    build:
      context: ../celeblur
      target: storage
    restart: always
    command: /bin/bash -c 'python3 app/storage/server.py'
    ports:
      - "5000:5000"
    volumes:
      - /opt:/opt
    working_dir: /workdir/
    environment:
      PORT: 5000

  engine:
    build:
      context: ../celeblur
      target: storage
    restart: always
    command: /bin/bash -c 'sleep 20 && python3 app/engine/server.py'
    ports:
      - "5001:5001"
    volumes:
      - /opt:/opt 
    working_dir: /workdir/
    environment:
      PYTHONPATH: /workdir
      PORT: 5001