version: '3.8'

services:
  core:
    build:
      context: ../app
      target: app
    command: /bin/bash -c 'python3 manage.py'
    ports:
      - "80:8080"
    working_dir: /mnt/
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
